name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      image: vault-secret-fetcher:${GITHUB_SHA}
      E2E_VAULT_SECRET_FETCHER_IMAGE: $image

    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      run: scripts/build.sh

    - name: Test
      run: scripts/test.sh
