name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      run: image="vault-secret-fetcher:${GITHUB_SHA::8}" scripts/build.sh

    - name: Test
      run: E2E_VAULT_SECRET_FETCHER_IMAGE="vault-secret-fetcher:${GITHUB_SHA::8}" scripts/test.sh
